# Generated by Django 3.2.17 on 2023-02-06 11:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
