# Generated by Django 3.2.17 on 2023-02-12 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardBase', '0002_alter_announcement_announcement_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='response_announcement',
            new_name='announcement',
        ),
    ]
