# Generated by Django 3.2.17 on 2023-02-12 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BoardBase', '0003_rename_response_announcement_response_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_response', to='BoardBase.announcement'),
        ),
    ]
