# Generated by Django 3.2.17 on 2023-02-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardBase', '0004_alter_response_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='activated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
